//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Formulario.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebEjercicio2Soap", Namespace="http://tempuri.org/")]
    public partial class WebEjercicio2 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SincronizarFechaHoraOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerCufdOperationCompleted;
        
        private System.Threading.SendOrPostCallback EmitirFacturaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebEjercicio2() {
            this.Url = global::Formulario.Properties.Settings.Default.Formulario_localhost_WebEjercicio2;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SincronizarFechaHoraCompletedEventHandler SincronizarFechaHoraCompleted;
        
        /// <remarks/>
        public event ObtenerCufdCompletedEventHandler ObtenerCufdCompleted;
        
        /// <remarks/>
        public event EmitirFacturaCompletedEventHandler EmitirFacturaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SincronizarFechaHora", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SincronizarFechaHora() {
            object[] results = this.Invoke("SincronizarFechaHora", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SincronizarFechaHoraAsync() {
            this.SincronizarFechaHoraAsync(null);
        }
        
        /// <remarks/>
        public void SincronizarFechaHoraAsync(object userState) {
            if ((this.SincronizarFechaHoraOperationCompleted == null)) {
                this.SincronizarFechaHoraOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSincronizarFechaHoraOperationCompleted);
            }
            this.InvokeAsync("SincronizarFechaHora", new object[0], this.SincronizarFechaHoraOperationCompleted, userState);
        }
        
        private void OnSincronizarFechaHoraOperationCompleted(object arg) {
            if ((this.SincronizarFechaHoraCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SincronizarFechaHoraCompleted(this, new SincronizarFechaHoraCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerCufd", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ObtenerCufd(string idambiente, string modalidad, string nit) {
            object[] results = this.Invoke("ObtenerCufd", new object[] {
                        idambiente,
                        modalidad,
                        nit});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerCufdAsync(string idambiente, string modalidad, string nit) {
            this.ObtenerCufdAsync(idambiente, modalidad, nit, null);
        }
        
        /// <remarks/>
        public void ObtenerCufdAsync(string idambiente, string modalidad, string nit, object userState) {
            if ((this.ObtenerCufdOperationCompleted == null)) {
                this.ObtenerCufdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerCufdOperationCompleted);
            }
            this.InvokeAsync("ObtenerCufd", new object[] {
                        idambiente,
                        modalidad,
                        nit}, this.ObtenerCufdOperationCompleted, userState);
        }
        
        private void OnObtenerCufdOperationCompleted(object arg) {
            if ((this.ObtenerCufdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerCufdCompleted(this, new ObtenerCufdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EmitirFactura", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EmitirFactura(int idambiente, int nit, string cufd, int modalidad, Factura factura) {
            object[] results = this.Invoke("EmitirFactura", new object[] {
                        idambiente,
                        nit,
                        cufd,
                        modalidad,
                        factura});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EmitirFacturaAsync(int idambiente, int nit, string cufd, int modalidad, Factura factura) {
            this.EmitirFacturaAsync(idambiente, nit, cufd, modalidad, factura, null);
        }
        
        /// <remarks/>
        public void EmitirFacturaAsync(int idambiente, int nit, string cufd, int modalidad, Factura factura, object userState) {
            if ((this.EmitirFacturaOperationCompleted == null)) {
                this.EmitirFacturaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEmitirFacturaOperationCompleted);
            }
            this.InvokeAsync("EmitirFactura", new object[] {
                        idambiente,
                        nit,
                        cufd,
                        modalidad,
                        factura}, this.EmitirFacturaOperationCompleted, userState);
        }
        
        private void OnEmitirFacturaOperationCompleted(object arg) {
            if ((this.EmitirFacturaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EmitirFacturaCompleted(this, new EmitirFacturaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Factura {
        
        private string nitField;
        
        private string razonSocialField;
        
        private string fechaField;
        
        private string cufField;
        
        private string tipoDocumentoClienteField;
        
        private string nombreClienteField;
        
        private string numeroFacturaField;
        
        /// <remarks/>
        public string Nit {
            get {
                return this.nitField;
            }
            set {
                this.nitField = value;
            }
        }
        
        /// <remarks/>
        public string RazonSocial {
            get {
                return this.razonSocialField;
            }
            set {
                this.razonSocialField = value;
            }
        }
        
        /// <remarks/>
        public string Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        public string Cuf {
            get {
                return this.cufField;
            }
            set {
                this.cufField = value;
            }
        }
        
        /// <remarks/>
        public string TipoDocumentoCliente {
            get {
                return this.tipoDocumentoClienteField;
            }
            set {
                this.tipoDocumentoClienteField = value;
            }
        }
        
        /// <remarks/>
        public string NombreCliente {
            get {
                return this.nombreClienteField;
            }
            set {
                this.nombreClienteField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroFactura {
            get {
                return this.numeroFacturaField;
            }
            set {
                this.numeroFacturaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void SincronizarFechaHoraCompletedEventHandler(object sender, SincronizarFechaHoraCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SincronizarFechaHoraCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SincronizarFechaHoraCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void ObtenerCufdCompletedEventHandler(object sender, ObtenerCufdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerCufdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerCufdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void EmitirFacturaCompletedEventHandler(object sender, EmitirFacturaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EmitirFacturaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EmitirFacturaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591