//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Formulario.ServicePregunta1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicePregunta1.pregunta1Soap")]
    public interface pregunta1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Formulario.ServicePregunta1.HelloWorldResponse HelloWorld(Formulario.ServicePregunta1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Formulario.ServicePregunta1.HelloWorldResponse> HelloWorldAsync(Formulario.ServicePregunta1.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento moneda del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerCotizacion", ReplyAction="*")]
        Formulario.ServicePregunta1.obtenerCotizacionResponse obtenerCotizacion(Formulario.ServicePregunta1.obtenerCotizacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerCotizacion", ReplyAction="*")]
        System.Threading.Tasks.Task<Formulario.ServicePregunta1.obtenerCotizacionResponse> obtenerCotizacionAsync(Formulario.ServicePregunta1.obtenerCotizacionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Formulario.ServicePregunta1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Formulario.ServicePregunta1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Formulario.ServicePregunta1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Formulario.ServicePregunta1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerCotizacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerCotizacion", Namespace="http://tempuri.org/", Order=0)]
        public Formulario.ServicePregunta1.obtenerCotizacionRequestBody Body;
        
        public obtenerCotizacionRequest() {
        }
        
        public obtenerCotizacionRequest(Formulario.ServicePregunta1.obtenerCotizacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerCotizacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string moneda;
        
        public obtenerCotizacionRequestBody() {
        }
        
        public obtenerCotizacionRequestBody(string moneda) {
            this.moneda = moneda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerCotizacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerCotizacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public Formulario.ServicePregunta1.obtenerCotizacionResponseBody Body;
        
        public obtenerCotizacionResponse() {
        }
        
        public obtenerCotizacionResponse(Formulario.ServicePregunta1.obtenerCotizacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerCotizacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double obtenerCotizacionResult;
        
        public obtenerCotizacionResponseBody() {
        }
        
        public obtenerCotizacionResponseBody(double obtenerCotizacionResult) {
            this.obtenerCotizacionResult = obtenerCotizacionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface pregunta1SoapChannel : Formulario.ServicePregunta1.pregunta1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class pregunta1SoapClient : System.ServiceModel.ClientBase<Formulario.ServicePregunta1.pregunta1Soap>, Formulario.ServicePregunta1.pregunta1Soap {
        
        public pregunta1SoapClient() {
        }
        
        public pregunta1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public pregunta1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public pregunta1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public pregunta1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Formulario.ServicePregunta1.HelloWorldResponse Formulario.ServicePregunta1.pregunta1Soap.HelloWorld(Formulario.ServicePregunta1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Formulario.ServicePregunta1.HelloWorldRequest inValue = new Formulario.ServicePregunta1.HelloWorldRequest();
            inValue.Body = new Formulario.ServicePregunta1.HelloWorldRequestBody();
            Formulario.ServicePregunta1.HelloWorldResponse retVal = ((Formulario.ServicePregunta1.pregunta1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Formulario.ServicePregunta1.HelloWorldResponse> Formulario.ServicePregunta1.pregunta1Soap.HelloWorldAsync(Formulario.ServicePregunta1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Formulario.ServicePregunta1.HelloWorldResponse> HelloWorldAsync() {
            Formulario.ServicePregunta1.HelloWorldRequest inValue = new Formulario.ServicePregunta1.HelloWorldRequest();
            inValue.Body = new Formulario.ServicePregunta1.HelloWorldRequestBody();
            return ((Formulario.ServicePregunta1.pregunta1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Formulario.ServicePregunta1.obtenerCotizacionResponse Formulario.ServicePregunta1.pregunta1Soap.obtenerCotizacion(Formulario.ServicePregunta1.obtenerCotizacionRequest request) {
            return base.Channel.obtenerCotizacion(request);
        }
        
        public double obtenerCotizacion(string moneda) {
            Formulario.ServicePregunta1.obtenerCotizacionRequest inValue = new Formulario.ServicePregunta1.obtenerCotizacionRequest();
            inValue.Body = new Formulario.ServicePregunta1.obtenerCotizacionRequestBody();
            inValue.Body.moneda = moneda;
            Formulario.ServicePregunta1.obtenerCotizacionResponse retVal = ((Formulario.ServicePregunta1.pregunta1Soap)(this)).obtenerCotizacion(inValue);
            return retVal.Body.obtenerCotizacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Formulario.ServicePregunta1.obtenerCotizacionResponse> Formulario.ServicePregunta1.pregunta1Soap.obtenerCotizacionAsync(Formulario.ServicePregunta1.obtenerCotizacionRequest request) {
            return base.Channel.obtenerCotizacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Formulario.ServicePregunta1.obtenerCotizacionResponse> obtenerCotizacionAsync(string moneda) {
            Formulario.ServicePregunta1.obtenerCotizacionRequest inValue = new Formulario.ServicePregunta1.obtenerCotizacionRequest();
            inValue.Body = new Formulario.ServicePregunta1.obtenerCotizacionRequestBody();
            inValue.Body.moneda = moneda;
            return ((Formulario.ServicePregunta1.pregunta1Soap)(this)).obtenerCotizacionAsync(inValue);
        }
    }
}
