//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Formulario.ServiceEjercicio2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Factura", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Factura : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazonSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CufField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDocumentoClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroFacturaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nit {
            get {
                return this.NitField;
            }
            set {
                if ((object.ReferenceEquals(this.NitField, value) != true)) {
                    this.NitField = value;
                    this.RaisePropertyChanged("Nit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RazonSocial {
            get {
                return this.RazonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.RazonSocialField, value) != true)) {
                    this.RazonSocialField = value;
                    this.RaisePropertyChanged("RazonSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaField, value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Cuf {
            get {
                return this.CufField;
            }
            set {
                if ((object.ReferenceEquals(this.CufField, value) != true)) {
                    this.CufField = value;
                    this.RaisePropertyChanged("Cuf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string TipoDocumentoCliente {
            get {
                return this.TipoDocumentoClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocumentoClienteField, value) != true)) {
                    this.TipoDocumentoClienteField = value;
                    this.RaisePropertyChanged("TipoDocumentoCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string NombreCliente {
            get {
                return this.NombreClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreClienteField, value) != true)) {
                    this.NombreClienteField = value;
                    this.RaisePropertyChanged("NombreCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string NumeroFactura {
            get {
                return this.NumeroFacturaField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroFacturaField, value) != true)) {
                    this.NumeroFacturaField = value;
                    this.RaisePropertyChanged("NumeroFactura");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceEjercicio2.WebEjercicio2Soap")]
    public interface WebEjercicio2Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento SincronizarFechaHoraResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SincronizarFechaHora", ReplyAction="*")]
        Formulario.ServiceEjercicio2.SincronizarFechaHoraResponse SincronizarFechaHora(Formulario.ServiceEjercicio2.SincronizarFechaHoraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SincronizarFechaHora", ReplyAction="*")]
        System.Threading.Tasks.Task<Formulario.ServiceEjercicio2.SincronizarFechaHoraResponse> SincronizarFechaHoraAsync(Formulario.ServiceEjercicio2.SincronizarFechaHoraRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento idambiente del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCufd", ReplyAction="*")]
        Formulario.ServiceEjercicio2.ObtenerCufdResponse ObtenerCufd(Formulario.ServiceEjercicio2.ObtenerCufdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCufd", ReplyAction="*")]
        System.Threading.Tasks.Task<Formulario.ServiceEjercicio2.ObtenerCufdResponse> ObtenerCufdAsync(Formulario.ServiceEjercicio2.ObtenerCufdRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cufd del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmitirFactura", ReplyAction="*")]
        Formulario.ServiceEjercicio2.EmitirFacturaResponse EmitirFactura(Formulario.ServiceEjercicio2.EmitirFacturaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmitirFactura", ReplyAction="*")]
        System.Threading.Tasks.Task<Formulario.ServiceEjercicio2.EmitirFacturaResponse> EmitirFacturaAsync(Formulario.ServiceEjercicio2.EmitirFacturaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SincronizarFechaHoraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SincronizarFechaHora", Namespace="http://tempuri.org/", Order=0)]
        public Formulario.ServiceEjercicio2.SincronizarFechaHoraRequestBody Body;
        
        public SincronizarFechaHoraRequest() {
        }
        
        public SincronizarFechaHoraRequest(Formulario.ServiceEjercicio2.SincronizarFechaHoraRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SincronizarFechaHoraRequestBody {
        
        public SincronizarFechaHoraRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SincronizarFechaHoraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SincronizarFechaHoraResponse", Namespace="http://tempuri.org/", Order=0)]
        public Formulario.ServiceEjercicio2.SincronizarFechaHoraResponseBody Body;
        
        public SincronizarFechaHoraResponse() {
        }
        
        public SincronizarFechaHoraResponse(Formulario.ServiceEjercicio2.SincronizarFechaHoraResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SincronizarFechaHoraResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SincronizarFechaHoraResult;
        
        public SincronizarFechaHoraResponseBody() {
        }
        
        public SincronizarFechaHoraResponseBody(string SincronizarFechaHoraResult) {
            this.SincronizarFechaHoraResult = SincronizarFechaHoraResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCufdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCufd", Namespace="http://tempuri.org/", Order=0)]
        public Formulario.ServiceEjercicio2.ObtenerCufdRequestBody Body;
        
        public ObtenerCufdRequest() {
        }
        
        public ObtenerCufdRequest(Formulario.ServiceEjercicio2.ObtenerCufdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCufdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idambiente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string modalidad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nit;
        
        public ObtenerCufdRequestBody() {
        }
        
        public ObtenerCufdRequestBody(string idambiente, string modalidad, string nit) {
            this.idambiente = idambiente;
            this.modalidad = modalidad;
            this.nit = nit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCufdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCufdResponse", Namespace="http://tempuri.org/", Order=0)]
        public Formulario.ServiceEjercicio2.ObtenerCufdResponseBody Body;
        
        public ObtenerCufdResponse() {
        }
        
        public ObtenerCufdResponse(Formulario.ServiceEjercicio2.ObtenerCufdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCufdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtenerCufdResult;
        
        public ObtenerCufdResponseBody() {
        }
        
        public ObtenerCufdResponseBody(string ObtenerCufdResult) {
            this.ObtenerCufdResult = ObtenerCufdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmitirFacturaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmitirFactura", Namespace="http://tempuri.org/", Order=0)]
        public Formulario.ServiceEjercicio2.EmitirFacturaRequestBody Body;
        
        public EmitirFacturaRequest() {
        }
        
        public EmitirFacturaRequest(Formulario.ServiceEjercicio2.EmitirFacturaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EmitirFacturaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idambiente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int nit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cufd;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int modalidad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public Formulario.ServiceEjercicio2.Factura factura;
        
        public EmitirFacturaRequestBody() {
        }
        
        public EmitirFacturaRequestBody(int idambiente, int nit, string cufd, int modalidad, Formulario.ServiceEjercicio2.Factura factura) {
            this.idambiente = idambiente;
            this.nit = nit;
            this.cufd = cufd;
            this.modalidad = modalidad;
            this.factura = factura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmitirFacturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmitirFacturaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Formulario.ServiceEjercicio2.EmitirFacturaResponseBody Body;
        
        public EmitirFacturaResponse() {
        }
        
        public EmitirFacturaResponse(Formulario.ServiceEjercicio2.EmitirFacturaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EmitirFacturaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EmitirFacturaResult;
        
        public EmitirFacturaResponseBody() {
        }
        
        public EmitirFacturaResponseBody(string EmitirFacturaResult) {
            this.EmitirFacturaResult = EmitirFacturaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebEjercicio2SoapChannel : Formulario.ServiceEjercicio2.WebEjercicio2Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebEjercicio2SoapClient : System.ServiceModel.ClientBase<Formulario.ServiceEjercicio2.WebEjercicio2Soap>, Formulario.ServiceEjercicio2.WebEjercicio2Soap {
        
        public WebEjercicio2SoapClient() {
        }
        
        public WebEjercicio2SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebEjercicio2SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebEjercicio2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebEjercicio2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Formulario.ServiceEjercicio2.SincronizarFechaHoraResponse Formulario.ServiceEjercicio2.WebEjercicio2Soap.SincronizarFechaHora(Formulario.ServiceEjercicio2.SincronizarFechaHoraRequest request) {
            return base.Channel.SincronizarFechaHora(request);
        }
        
        public string SincronizarFechaHora() {
            Formulario.ServiceEjercicio2.SincronizarFechaHoraRequest inValue = new Formulario.ServiceEjercicio2.SincronizarFechaHoraRequest();
            inValue.Body = new Formulario.ServiceEjercicio2.SincronizarFechaHoraRequestBody();
            Formulario.ServiceEjercicio2.SincronizarFechaHoraResponse retVal = ((Formulario.ServiceEjercicio2.WebEjercicio2Soap)(this)).SincronizarFechaHora(inValue);
            return retVal.Body.SincronizarFechaHoraResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Formulario.ServiceEjercicio2.SincronizarFechaHoraResponse> Formulario.ServiceEjercicio2.WebEjercicio2Soap.SincronizarFechaHoraAsync(Formulario.ServiceEjercicio2.SincronizarFechaHoraRequest request) {
            return base.Channel.SincronizarFechaHoraAsync(request);
        }
        
        public System.Threading.Tasks.Task<Formulario.ServiceEjercicio2.SincronizarFechaHoraResponse> SincronizarFechaHoraAsync() {
            Formulario.ServiceEjercicio2.SincronizarFechaHoraRequest inValue = new Formulario.ServiceEjercicio2.SincronizarFechaHoraRequest();
            inValue.Body = new Formulario.ServiceEjercicio2.SincronizarFechaHoraRequestBody();
            return ((Formulario.ServiceEjercicio2.WebEjercicio2Soap)(this)).SincronizarFechaHoraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Formulario.ServiceEjercicio2.ObtenerCufdResponse Formulario.ServiceEjercicio2.WebEjercicio2Soap.ObtenerCufd(Formulario.ServiceEjercicio2.ObtenerCufdRequest request) {
            return base.Channel.ObtenerCufd(request);
        }
        
        public string ObtenerCufd(string idambiente, string modalidad, string nit) {
            Formulario.ServiceEjercicio2.ObtenerCufdRequest inValue = new Formulario.ServiceEjercicio2.ObtenerCufdRequest();
            inValue.Body = new Formulario.ServiceEjercicio2.ObtenerCufdRequestBody();
            inValue.Body.idambiente = idambiente;
            inValue.Body.modalidad = modalidad;
            inValue.Body.nit = nit;
            Formulario.ServiceEjercicio2.ObtenerCufdResponse retVal = ((Formulario.ServiceEjercicio2.WebEjercicio2Soap)(this)).ObtenerCufd(inValue);
            return retVal.Body.ObtenerCufdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Formulario.ServiceEjercicio2.ObtenerCufdResponse> Formulario.ServiceEjercicio2.WebEjercicio2Soap.ObtenerCufdAsync(Formulario.ServiceEjercicio2.ObtenerCufdRequest request) {
            return base.Channel.ObtenerCufdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Formulario.ServiceEjercicio2.ObtenerCufdResponse> ObtenerCufdAsync(string idambiente, string modalidad, string nit) {
            Formulario.ServiceEjercicio2.ObtenerCufdRequest inValue = new Formulario.ServiceEjercicio2.ObtenerCufdRequest();
            inValue.Body = new Formulario.ServiceEjercicio2.ObtenerCufdRequestBody();
            inValue.Body.idambiente = idambiente;
            inValue.Body.modalidad = modalidad;
            inValue.Body.nit = nit;
            return ((Formulario.ServiceEjercicio2.WebEjercicio2Soap)(this)).ObtenerCufdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Formulario.ServiceEjercicio2.EmitirFacturaResponse Formulario.ServiceEjercicio2.WebEjercicio2Soap.EmitirFactura(Formulario.ServiceEjercicio2.EmitirFacturaRequest request) {
            return base.Channel.EmitirFactura(request);
        }
        
        public string EmitirFactura(int idambiente, int nit, string cufd, int modalidad, Formulario.ServiceEjercicio2.Factura factura) {
            Formulario.ServiceEjercicio2.EmitirFacturaRequest inValue = new Formulario.ServiceEjercicio2.EmitirFacturaRequest();
            inValue.Body = new Formulario.ServiceEjercicio2.EmitirFacturaRequestBody();
            inValue.Body.idambiente = idambiente;
            inValue.Body.nit = nit;
            inValue.Body.cufd = cufd;
            inValue.Body.modalidad = modalidad;
            inValue.Body.factura = factura;
            Formulario.ServiceEjercicio2.EmitirFacturaResponse retVal = ((Formulario.ServiceEjercicio2.WebEjercicio2Soap)(this)).EmitirFactura(inValue);
            return retVal.Body.EmitirFacturaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Formulario.ServiceEjercicio2.EmitirFacturaResponse> Formulario.ServiceEjercicio2.WebEjercicio2Soap.EmitirFacturaAsync(Formulario.ServiceEjercicio2.EmitirFacturaRequest request) {
            return base.Channel.EmitirFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Formulario.ServiceEjercicio2.EmitirFacturaResponse> EmitirFacturaAsync(int idambiente, int nit, string cufd, int modalidad, Formulario.ServiceEjercicio2.Factura factura) {
            Formulario.ServiceEjercicio2.EmitirFacturaRequest inValue = new Formulario.ServiceEjercicio2.EmitirFacturaRequest();
            inValue.Body = new Formulario.ServiceEjercicio2.EmitirFacturaRequestBody();
            inValue.Body.idambiente = idambiente;
            inValue.Body.nit = nit;
            inValue.Body.cufd = cufd;
            inValue.Body.modalidad = modalidad;
            inValue.Body.factura = factura;
            return ((Formulario.ServiceEjercicio2.WebEjercicio2Soap)(this)).EmitirFacturaAsync(inValue);
        }
    }
}
